- href: /images/m2/prolabels/config/onsale-category-0.png
  src: /images/m2/prolabels/config/onsale-category-0-small.png
  title: Category page labels config - initial state
  w: 716
  h: 410
- href: /images/m2/prolabels/config/onsale-category-1.png
  src: /images/m2/prolabels/config/onsale-category-1-small.png
  title: Category page labels config - presets loaded
  w: 716
  h: 530
- href: /images/m2/prolabels/config/onsale-category-2.png
  src: /images/m2/prolabels/config/onsale-category-2-small.png
  title: Category page labels config - advanced optiones shown
  w: 716
  h: 960
