- href: /images/m2/prolabels/config/onsale-product-0.png
  src: /images/m2/prolabels/config/onsale-product-0-small.png
  title: Product page labels config - initial state
  w: 716
  h: 548
- href: /images/m2/prolabels/config/onsale-product-1.png
  src: /images/m2/prolabels/config/onsale-product-1-small.png
  title: Product page labels config - presets loaded
  w: 716
  h: 548
- href: /images/m2/prolabels/config/onsale-product-2.png
  src: /images/m2/prolabels/config/onsale-product-2-small.png
  title: Product page labels config - advanced optiones shown
  w: 716
  h: 960
