# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://quantizedai.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Quantized AI
# Description of the Site
description:  A platform dedicated to deep learning optimization and quantization
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
#site-keywords: Deep Learning, Optimization, Quantization, AI, Machine Learning
site-keywords: 
  - Deep Learning
  - AI Optimization
  - AI Quantization
  - Machine Learning Optimization
  - Model Optimization
  - Neural Network Compression
  - Efficient AI Solutions
  - Real-time AI Inference
  - Scalable AI
  - Quantized AI
  - AI Deployment
  - Edge AI
  - Deep Learning Frameworks
  - AI Performance Improvement
  - AI for Businesses
  - QuantizedAI

# Your Google Search Console verification code
# google-verification: "your-verification-code"

# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: anistaluqdar@gmail.com
#facebook_username: 
#twitter_username: 
#instagram_username: 
linkedin_username: quantized_ai
github_username:  quantizedai
youtube_channel_id: UCg_Q_mHzsuomn8fVvpdCFDw
reddit_username: /quantizedai
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: quantizedai


# Authors Information
authors:
  John Doe:
    name: John Doe
    bio: Lead Researcher in model optimization.
    image: https://example.com/johndoe.jpg
    
    
  Jane Smith:
    name: Jane Smith
    bio: Software Engineer specializing in AI deployment.
    image: https://example.com/janesmith.jpg
    url: https://twitter.com/janesmith

# Default Author Information
# Name of the Author
author-name: Quantized AI
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Quantized AI is a cutting-edge team of deep learning researchers and practitioners dedicated to advancing optimization techniques and efficient inference methods. We specialize in improving model performance, reducing computational costs, and enabling real-time, scalable AI solutions across industries. Our research focuses on developing state-of-the-art methods, including quantization, pruning, knowledge distillation, and model compression, to make deep learning models faster, more resource-efficient, and easier to deploy on edge devices and cloud platforms. Through a deep understanding of model architecture and hardware constraints, we aim to push the boundaries of AI scalability, ensuring that complex models can be deployed with minimal computational overhead while maintaining accuracy and reliability. Quantized AI is committed to transforming how industries leverage AI, providing innovative solutions that accelerate decision-making and optimize performance across sectors such as healthcare, finance, robotics, and more.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/quantizedai

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
