title: "Quantized AI"
description: "Optimizing deep learning with cutting-edge quantization techniques"
url: "https://QuantizedAI.com"
baseurl: ""
<<<<<<< HEAD
author: Quantized AI
email: info@QuantizedAI.com
twitter_username: QuantizedAI
github_username: QuantizedAI
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
=======
url: "https://quantizedai.com/"

repository: quantizedai/quantizedai.github.io

permalink: pretty

safe: true
lsi: false

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 2..5

exclude:
  - bower_components
  - css/app.scss
  - css/syntax.scss
  - js/app.js
  - js/search.js
  - node_modules

github:
  repository_url: https://github.com/quantizedai/quantizedai.github.io

prose:
  siteurl: "https://quantizedai.github.io/"
  media: "media"
  ignore:
    - .gitignore
    - bower.json
    - _config.yml
    - search.json
    - /_includes
    - /_layouts
    - /_posts
    - /bower_components
>>>>>>> refs/remotes/origin/main
