- title: Layout section
  href: /images/m2/argento/marketplace/theme-editor/config/layout.png
  src: /images/m2/argento/marketplace/theme-editor/config/small/layout.png
  w: 1481
  h: 891
- title: Header section
  href: /images/m2/argento/marketplace/theme-editor/config/header.png
  src: /images/m2/argento/marketplace/theme-editor/config/small/header.png
  w: 1468
  h: 1063
- title: Footer section
  href: /images/m2/argento/marketplace/theme-editor/config/footer.png
  src: /images/m2/argento/marketplace/theme-editor/config/small/footer.png
  w: 1465
  h: 1217
- title: Buttons section
  href: /images/m2/argento/marketplace/theme-editor/config/buttons.png
  src: /images/m2/argento/marketplace/theme-editor/config/small/buttons.png
  w: 1458
  h: 1018
- title: Fonts and Colors section
  href: /images/m2/argento/marketplace/theme-editor/config/fonts.png
  src: /images/m2/argento/marketplace/theme-editor/config/small/fonts.png
  w: 1456
  h: 520
