- title: Layout section
  href: /images/m2/argento/essence/theme-editor/config/layout.png
  src: /images/m2/argento/essence/theme-editor/config/small/layout.png
  w: 761
  h: 636
- title: Header top toolbar
  href: /images/m2/argento/essence/theme-editor/config/header-top-toolbar.png
  src: /images/m2/argento/essence/theme-editor/config/small/header-top-toolbar.png
  w: 726
  h: 635
- title: Navigation
  href: /images/m2/argento/essence/theme-editor/config/navigation.png
  src: /images/m2/argento/essence/theme-editor/config/small/navigation.png
  w: 726
  h: 1957
- title: Footer top toolbar
  href: /images/m2/argento/essence/theme-editor/config/footer-top-toolbar.png
  src: /images/m2/argento/essence/theme-editor/config/small/footer-top-toolbar.png
  w: 726
  h: 563
- title: Footer content
  href: /images/m2/argento/essence/theme-editor/config/footer-content.png
  src: /images/m2/argento/essence/theme-editor/config/small/footer-content.png
  w: 726
  h: 594
- title: Footer bottom toolbar
  href: /images/m2/argento/essence/theme-editor/config/footer-bottom-toolbar.png
  src: /images/m2/argento/essence/theme-editor/config/small/footer-bottom-toolbar.png
  w: 726
  h: 550
- title: Tabs
  href: /images/m2/argento/essence/theme-editor/config/product-and-homepage-tabs.png
  src: /images/m2/argento/essence/theme-editor/config/small/product-and-homepage-tabs.png
  w: 760
  h: 826
- title: Buttons
  href: /images/m2/argento/essence/theme-editor/config/buttons.png
  src: /images/m2/argento/essence/theme-editor/config/small/buttons.png
  w: 760
  h: 606
- title: Fonts
  href: /images/m2/argento/essence/theme-editor/config/fonts.png
  src: /images/m2/argento/essence/theme-editor/config/small/fonts.png
  w: 760
  h: 928
- title: Additional css
  href: /images/m2/argento/essence/theme-editor/config/additional-css.png
  src: /images/m2/argento/essence/theme-editor/config/small/additional-css.png
  w: 760
  h: 192
