- title: Layout section
  href: /images/m2/argento/stripes/theme-editor/config/layout.png
  src: /images/m2/argento/stripes/theme-editor/config/layout-small.png
  w: 900
  h: 844
- title: Header section
  href: /images/m2/argento/stripes/theme-editor/config/header.png
  src: /images/m2/argento/stripes/theme-editor/config/header-small.png
  w: 900
  h: 708
- title: Header buttons section
  href: /images/m2/argento/stripes/theme-editor/config/header-buttons.png
  src: /images/m2/argento/stripes/theme-editor/config/header-buttons-small.png
  w: 900
  h: 616
- title: Navigation section
  href: /images/m2/argento/stripes/theme-editor/config/navigation.png
  src: /images/m2/argento/stripes/theme-editor/config/navigation-small.png
  w: 900
  h: 2000
- title: Footer section
  href: /images/m2/argento/stripes/theme-editor/config/footer.png
  src: /images/m2/argento/stripes/theme-editor/config/footer-small.png
  w: 900
  h: 716
- title: Footer toolbar section
  href: /images/m2/argento/stripes/theme-editor/config/footer-toolbar.png
  src: /images/m2/argento/stripes/theme-editor/config/footer-toolbar-small.png
  w: 900
  h: 640
- title: Buttons section
  href: /images/m2/argento/stripes/theme-editor/config/buttons.png
  src: /images/m2/argento/stripes/theme-editor/config/buttons-small.png
  w: 900
  h: 1082
- title: Buttons section
  href: /images/m2/argento/stripes/theme-editor/config/fonts.png
  src: /images/m2/argento/stripes/theme-editor/config/fonts-small.png
  w: 900
  h: 868
- title: Additional css
  href: /images/m2/argento/stripes/theme-editor/config/additional-css.png
  src: /images/m2/argento/stripes/theme-editor/config/additional-css-small.png
  w: 900
  h: 388
