- title: Layout section
  href: /images/m2/argento/home/theme-editor/config/layout.png
  src: /images/m2/argento/home/theme-editor/config/small/layout.png
  w: 757
  h: 868
- title: Header section
  href: /images/m2/argento/home/theme-editor/config/header.png
  src: /images/m2/argento/home/theme-editor/config/small/header.png
  w: 756
  h: 911
- title: Footer section
  href: /images/m2/argento/home/theme-editor/config/footer.png
  src: /images/m2/argento/home/theme-editor/config/small/footer.png
  w: 753
  h: 891
- title: Buttons section
  href: /images/m2/argento/home/theme-editor/config/buttons.png
  src: /images/m2/argento/home/theme-editor/config/small/buttons.png
  w: 748
  h: 922
- title: Fonts and Colors section
  href: /images/m2/argento/home/theme-editor/config/fonts.png
  src: /images/m2/argento/home/theme-editor/config/small/fonts.png
  w: 752
  h: 587
