- title: Layout section
  href: /images/m2/argento/flat/theme-editor/config/layout.png
  src: /images/m2/argento/flat/theme-editor/config/small/layout.png
  w: 796
  h: 607
- title: Header
  href: /images/m2/argento/flat/theme-editor/config/header.png
  src: /images/m2/argento/flat/theme-editor/config/small/header.png
  w: 796
  h: 833
- title: Footer
  href: /images/m2/argento/flat/theme-editor/config/footer.png
  src: /images/m2/argento/flat/theme-editor/config/small/footer.png
  w: 796
  h: 597
- title: Tabs
  href: /images/m2/argento/flat/theme-editor/config/tabs.png
  src: /images/m2/argento/flat/theme-editor/config/small/tabs.png
  w: 796
  h: 767
- title: Buttons
  href: /images/m2/argento/flat/theme-editor/config/buttons.png
  src: /images/m2/argento/flat/theme-editor/config/small/buttons.png
  w: 796
  h: 821
- title: Fonts
  href: /images/m2/argento/flat/theme-editor/config/fonts.png
  src: /images/m2/argento/flat/theme-editor/config/small/fonts.png
  w: 796
  h: 814
- title: Additional css
  href: /images/m2/argento/flat/theme-editor/config/additional-css.png
  src: /images/m2/argento/flat/theme-editor/config/small/additional-css.png
  w: 796
  h: 212
