- title: Layout section
  href: /images/m2/argento/force/theme-editor/config/layout.png
  src: /images/m2/argento/force/theme-editor/config/small/layout.png
  w: 988
  h: 852
- title: Header section
  href: /images/m2/argento/force/theme-editor/config/header.png
  src: /images/m2/argento/force/theme-editor/config/small/header.png
  w: 988
  h: 1186
- title: Footer section
  href: /images/m2/argento/force/theme-editor/config/footer.png
  src: /images/m2/argento/force/theme-editor/config/small/footer.png
  w: 988
  h: 1263
- title: Buttons section
  href: /images/m2/argento/force/theme-editor/config/buttons.png
  src: /images/m2/argento/force/theme-editor/config/small/buttons.png
  w: 988
  h: 1200
- title: Fonts adn Colors section
  href: /images/m2/argento/force/theme-editor/config/fonts.png
  src: /images/m2/argento/force/theme-editor/config/small/fonts.png
  w: 988
  h: 611
