- title: Layout section
  href: /images/m2/argento/mall/theme-editor/config/layout.png
  src: /images/m2/argento/mall/theme-editor/config/small/layout.png
  w: 800
  h: 674
- title: Header
  href: /images/m2/argento/mall/theme-editor/config/header.png
  src: /images/m2/argento/mall/theme-editor/config/small/header.png
  w: 800
  h: 850
- title: Footer
  href: /images/m2/argento/mall/theme-editor/config/footer.png
  src: /images/m2/argento/mall/theme-editor/config/small/footer.png
  w: 800
  h: 860
- title: Tabs
  href: /images/m2/argento/mall/theme-editor/config/tabs.png
  src: /images/m2/argento/mall/theme-editor/config/small/tabs.png
  w: 800
  h: 825
- title: Buttons
  href: /images/m2/argento/mall/theme-editor/config/buttons.png
  src: /images/m2/argento/mall/theme-editor/config/small/buttons.png
  w: 800
  h: 735
- title: Fonts
  href: /images/m2/argento/mall/theme-editor/config/fonts.png
  src: /images/m2/argento/mall/theme-editor/config/small/fonts.png
  w: 800
  h: 825
- title: Additional css
  href: /images/m2/argento/pure2/theme-editor/config/additional-css.png
  src: /images/m2/argento/pure2/theme-editor/config/small/additional-css.png
  w: 800
  h: 344
